
name = "cloudflare-stitch"
main = "src/index.ts"
compatibility_date = "2024-12-30"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[placement]
mode = "smart"

[ai]
binding = "AI"

[[kv_namespaces]]
binding = "CHARACTERS"
id = "6ba0a9b00d4d46bc9108599661ed4c15"